# Generated by Django 6.1 on 2026-08-17 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=100, unique=True)),
                ('curr_symbol', models.CharField(max_length=10)),
                ('phone_code', models.CharField(max_length=10, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10, unique=True)),
                ('gst_code', models.CharField(max_length=10, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='locations.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=10)),
                ('phone_code', models.CharField(max_length=10, unique=True)),
                ('population', models.PositiveBigIntegerField()),
                ('avg_age', models.PositiveIntegerField()),
                ('num_of_adult_males', models.PositiveBigIntegerField()),
                ('num_of_adult_females', models.PositiveBigIntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.state')),
            ],
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='unique_state_name_per_country'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('country', 'state_code'), name='unique_state_code_per_country'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='unique_city_name_per_state'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'city_code'), name='unique_city_code_per_state'),
        ),
    ]
